[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
Import-Module (Join-Path $root 'scripts/Harness.Common.psm1') -Force
$passed=0
function Assert-True([bool]$Condition,[string]$Message){if(-not $Condition){throw "ASSERTION FAILED: $Message"};$script:passed++}
function New-TestRepo([string]$Name){
    $path=Join-Path ([IO.Path]::GetTempPath()) "Ralphy Project A Tests/$Name-$([Guid]::NewGuid().ToString('N'))";[IO.Directory]::CreateDirectory($path)|Out-Null
    & git -C $path init -b codex/project-a-harness|Out-Null;[IO.File]::WriteAllText((Join-Path $path 'README.md'),"test`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $path '.gitignore'),".harness/runtime/`n.logs/`n",[Text.UTF8Encoding]::new($false));& git -C $path add README.md .gitignore;& git -C $path commit -m baseline|Out-Null;return $path
}
function Write-TestPolicy([string]$Repo,[string]$Id,[bool]$Approval){
    $policy=[ordered]@{schema_version='project-a-task-policy-v1';id=$Id;title='contract fixture';risk=if($Approval){'high'}else{'medium'};mode='repo_only';depends_on=@();allowed_paths=@('project-a/fixture with space-非.txt');adapter_owned_paths=@("evidence/project-a/$Id.json");forbidden_operations=@('aws','az','terraform apply','terraform destroy','terraform import','terraform plan','credential read');validator_mutation_policy='no_tracked_writes';validators=@([ordered]@{id='scope';timeout_seconds=30;required=$true},[ordered]@{id='credential_boundary';timeout_seconds=30;required=$true},[ordered]@{id='forbidden_operations';timeout_seconds=30;required=$true},[ordered]@{id='secret_scan';timeout_seconds=30;required=$true});terra_attempt_limit=3;elapsed_limit_minutes=25;escalation=[ordered]@{consecutive_failures=2;same_error_count=2;no_diff_repairs=1;scope_escape=$true};approval=[ordered]@{required=$Approval;gate_id=if($Approval){'H0'}else{$null};stage='post_validation_pre_commit';approver='human';receipt_path=if($Approval){".harness/runtime/approvals/$Id.json"}else{$null};reason='contract'};expected_artifacts=@('project-a/fixture with space-非.txt');expected_evidence="evidence/project-a/$Id.json";commit_message="feat($Id): contract fixture";claims=[ordered]@{cloud_validated=$false;aws_implemented=$false;azure_implemented=$false}}
    Write-JsonNoBom -Path (Join-Path $Repo "project-a/harness/tasks/$Id.json") -Value $policy
}
function Set-AdapterEnvironment([string]$Repo,[string]$Id,[string]$LocalData){
    $env:HARNESS_ROOT=$Repo;$env:HARNESS_PROFILE_ID='project-a';$env:HARNESS_REAL_CODEX=Join-Path $root 'tests/fixtures/fake-codex.cmd';$env:HARNESS_RUN_ID='phase4-contract';$env:HARNESS_LOG_DIR=Join-Path $Repo '.logs';$env:HARNESS_BUNDLE_HASH=('D'*64);$env:HARNESS_VALIDATOR_HASH=(Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $root 'scripts/Invoke-ProjectAValidators.ps1')).Hash;$env:HARNESS_STDIN_OVERRIDE="[TASK:$Id] contract";$env:HARNESS_CONTRACT_ONLY='1';$env:HARNESS_FAKE_ALLOWED_PATH='project-a/fixture with space-非.txt';$env:HARNESS_FAKE_CALL_COUNT='.logs/calls.txt';$env:LOCALAPPDATA=$LocalData
}
function Clear-AdapterEnvironment { Remove-Item Env:HARNESS_ROOT,Env:HARNESS_PROFILE_ID,Env:HARNESS_REAL_CODEX,Env:HARNESS_RUN_ID,Env:HARNESS_LOG_DIR,Env:HARNESS_BUNDLE_HASH,Env:HARNESS_VALIDATOR_HASH,Env:HARNESS_STDIN_OVERRIDE,Env:HARNESS_CONTRACT_ONLY,Env:HARNESS_FAKE_ALLOWED_PATH,Env:HARNESS_FAKE_CALL_COUNT,Env:HARNESS_FAKE_ENV_DUMP,Env:HARNESS_FAKE_OUTPUT,Env:HARNESS_TEST_KILL_POINT,Env:HARNESS_APPROVE_TASK,Env:AWS_ACCESS_KEY_ID -ErrorAction SilentlyContinue }

$smoke=Read-HarnessProfile -Root $root -ProfileId smoke;$project=Read-HarnessProfile -Root $root -ProfileId project-a
Assert-True ($smoke.gate_kind -eq 'smoke_exact_fixture' -and $project.gate_kind -eq 'project_a_registry') 'explicit profiles keep smoke and Project A gates separate'
$traversalRejected=$false;try{[void](Resolve-PathUnderRoot -Root $root -RelativePath '../escape')}catch{$traversalRejected=$true};Assert-True $traversalRejected 'profile paths reject traversal'
$executionApproval=Read-JsonFile -Path (Join-Path $root 'project-a/harness/execution-approval.json');$executionBundle=& (Join-Path $root 'scripts/Get-ProjectAExecutionHash.ps1') -Root $root|ConvertFrom-Json
Assert-True (-not [bool]$executionApproval.execution_approved -and $executionApproval.status -eq 'phase4_proven_execution_approval_required') 'Phase 4 proof does not authorize live Project A execution'
Assert-True ([string]$executionApproval.execution_bundle_sha256 -eq [string]$executionBundle.sha256) 'execution approval pins every declared execution member'
Assert-True ([string]$executionApproval.validator_implementation_sha256 -eq (Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $root 'scripts/Invoke-ProjectAValidators.ps1')).Hash) 'execution approval pins validator implementation'
Assert-True ([string]$executionApproval.execution_hash_implementation_sha256 -eq (Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $root 'scripts/Get-ProjectAExecutionHash.ps1')).Hash) 'execution hash implementation is independently pinned'

$initial=@(New-RepoOnlyInitialCodexArguments -Arguments @('exec','--full-auto','--sandbox=danger-full-access','--json','[TASK:A-001]') -Model 'gpt-5.6-terra');$initialText=$initial -join ' '
Assert-True ($initialText -match 'workspace-write' -and $initialText -notmatch 'danger-full-access|--full-auto') 'repo-only initial calls enforce workspace-write'
Assert-True ($initialText -match 'network_access=false' -and $initialText -match 'web_search="disabled"' -and $initialText -match 'features.apps=false') 'repo-only initial calls explicitly disable command network, web, and apps'
Assert-True ($initialText -match 'shell_environment_policy.inherit="core"' -and $initialText -match 'CODEX_HOME') 'model shell receives a filtered core environment without Codex home'
$resume=@(New-RepoOnlyResumeCodexArguments -Model 'gpt-5.6-sol' -ThreadId 'thread' -Prompt 'repair' -OutputLastMessage $null) -join ' '
Assert-True ($resume -match 'sandbox_mode="workspace-write"' -and $resume -match 'network_access=false') 'resume calls preserve filesystem and network boundaries'

$psi=[Diagnostics.ProcessStartInfo]::new();$psi.Environment['AWS_ACCESS_KEY_ID']='AWS_ACCESS_KEY_ID_REDACTED';$psi.Environment['ARM_CLIENT_SECRET']='azure-secret';$psi.Environment['GH_TOKEN']='github-secret';$isolation=Join-Path $env:TEMP ('phase4-env-'+[Guid]::NewGuid().ToString('N'));Set-RepoOnlyProcessEnvironment -StartInfo $psi -IsolationRoot $isolation
Assert-True (-not $psi.Environment.ContainsKey('AWS_ACCESS_KEY_ID') -and -not $psi.Environment.ContainsKey('ARM_CLIENT_SECRET') -and -not $psi.Environment.ContainsKey('GH_TOKEN')) 'Codex process environment scrubs seeded cloud and GitHub credentials'
Assert-True ($psi.Environment['AWS_EC2_METADATA_DISABLED'] -eq 'true' -and (Test-Path $psi.Environment['AWS_CONFIG_FILE'])) 'Codex process disables metadata and redirects credential files'
Assert-True ($psi.Environment['USERPROFILE'] -eq $psi.Environment['HOME'] -and $psi.Environment['USERPROFILE'] -like "$isolation*") 'Codex process uses an isolated Windows profile and home'
Remove-Item -LiteralPath $isolation -Recurse -Force

$corpus='AWS_ACCESS_KEY_ID_REDACTED eyJabcdefgh.ijklmnop.qrstuvwx https://user:pass@example.test Set-Cookie: sid=abc -----BEGIN PRIVATE KEY-----'
$safe=Protect-LogText -Text $corpus;Assert-True ($safe -notmatch 'AWS_ACCESS_KEY_ID_REDACTED|eyJabcdefgh|user:pass|sid=abc|BEGIN PRIVATE KEY') 'redactor covers cloud keys, JWTs, URI credentials, cookies, and private-key headers'

$diffRepo=New-TestRepo 'canonical diff'
try{[IO.Directory]::CreateDirectory((Join-Path $diffRepo 'project-a'))|Out-Null;[IO.File]::WriteAllText((Join-Path $diffRepo 'project-a/fixture with space-非.txt'),"ok`n",[Text.UTF8Encoding]::new($false));$diff=Get-CanonicalDiffRecord -Root $diffRepo -AllowedPaths @('project-a/**');Assert-True ($diff.entries.Count -eq 1 -and $diff.entries[0].path -eq 'project-a/fixture with space-非.txt') 'canonical diff preserves spaces and non-ASCII paths';$first=$diff.sha256;[IO.File]::AppendAllText((Join-Path $diffRepo 'project-a/fixture with space-非.txt'),'x');$second=(Get-CanonicalDiffRecord -Root $diffRepo -AllowedPaths @('project-a/**')).sha256;Assert-True ($first -ne $second) 'one-byte changes invalidate exact diff fingerprints';&git -C $diffRepo add project-a;&git -C $diffRepo commit -m fixture|Out-Null;&git -C $diffRepo update-index --chmod=+x 'project-a/fixture with space-非.txt';$modeDiff=Get-CanonicalDiffRecord -Root $diffRepo -AllowedPaths @('project-a/**');Assert-True ($modeDiff.entries[0].old_mode -eq '100644' -and $modeDiff.entries[0].new_mode -eq '100755') 'canonical approval records bind Git mode-only changes'}finally{Remove-Item -LiteralPath $diffRepo -Recurse -Force}

$unknownRepo=New-TestRepo 'unknown validator'
try{Write-TestPolicy $unknownRepo 'A-006' $false;$unknownPath=Join-Path $unknownRepo 'project-a/harness/tasks/A-006.json';$unknown=Read-JsonFile -Path $unknownPath;$unknown.validators=@([pscustomobject]@{id='invented_shell_command';timeout_seconds=30;required=$true});Write-JsonNoBom -Path $unknownPath -Value $unknown;& git -C $unknownRepo add project-a/harness/tasks/A-006.json;& git -C $unknownRepo commit -m policy|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $unknownRepo 'project-a'))|Out-Null;[IO.File]::WriteAllText((Join-Path $unknownRepo 'project-a/fixture with space-非.txt'),"ok`n",[Text.UTF8Encoding]::new($false));$isolation=Join-Path $env:TEMP ('unknown-validator-'+[Guid]::NewGuid().ToString('N'));& pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Invoke-ProjectAValidators.ps1') -Root $unknownRepo -PolicyPath $unknownPath -IsolationRoot $isolation|Out-Null;Assert-True ($LASTEXITCODE -ne 0) 'validator registry fails closed on unknown IDs'}finally{Remove-Item -LiteralPath $unknownRepo -Recurse -Force;Remove-Item -LiteralPath $isolation -Recurse -Force -ErrorAction SilentlyContinue}

$semanticRepo=New-TestRepo 'semantic rejection';$semanticIsolation=Join-Path $env:TEMP ('semantic-validator-'+[Guid]::NewGuid().ToString('N'))
try{Write-TestPolicy $semanticRepo 'A-002' $true;$semanticPath=Join-Path $semanticRepo 'project-a/harness/tasks/A-002.json';$semantic=Read-JsonFile -Path $semanticPath;$semantic.validators=@([pscustomobject]@{id='organizations_semantics';timeout_seconds=30;required=$true});Write-JsonNoBom -Path $semanticPath -Value $semantic;& git -C $semanticRepo add project-a/harness/tasks/A-002.json;& git -C $semanticRepo commit -m policy|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $semanticRepo 'project-a'))|Out-Null;[IO.File]::WriteAllText((Join-Path $semanticRepo 'project-a/fixture with space-非.txt'),"garbage`n",[Text.UTF8Encoding]::new($false));& pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Invoke-ProjectAValidators.ps1') -Root $semanticRepo -PolicyPath $semanticPath -IsolationRoot $semanticIsolation|Out-Null;Assert-True ($LASTEXITCODE -ne 0) 'semantic validators reject non-empty garbage artifacts'}finally{Remove-Item -LiteralPath $semanticRepo -Recurse -Force;Remove-Item -LiteralPath $semanticIsolation -Recurse -Force -ErrorAction SilentlyContinue}

$noApprovalRepo=New-TestRepo 'adapter no approval';$localData=Join-Path $env:TEMP ('phase4-local-'+[Guid]::NewGuid().ToString('N'))
try{Write-TestPolicy $noApprovalRepo 'A-006' $false;& git -C $noApprovalRepo add project-a/harness/tasks/A-006.json;& git -C $noApprovalRepo commit -m policy|Out-Null;Set-AdapterEnvironment $noApprovalRepo 'A-006' $localData;$env:AWS_ACCESS_KEY_ID='AWS_ACCESS_KEY_ID_REDACTED';$env:HARNESS_FAKE_ENV_DUMP='.logs/env.txt';$env:HARNESS_FAKE_OUTPUT='raw-model-secret';& pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Invoke-ProjectAAdapter.ps1') exec --json '[TASK:A-006]'|Out-Null;Assert-True ($LASTEXITCODE -eq 0) 'A-006 deterministic adapter path completes without human receipt';Assert-True ((& git -C $noApprovalRepo log -1 --format=%s).Trim() -eq 'feat(A-006): contract fixture') 'adapter owns the gated A-006 commit';Assert-True (@(Get-ChangedPaths -Root $noApprovalRepo).Count -eq 0) 'A-006 adapter leaves a clean tree';$evidence=Get-Content -Raw (Join-Path $noApprovalRepo 'evidence/project-a/A-006.json')|ConvertFrom-Json;Assert-True ($evidence.cloud_validated -eq $false -and $evidence.aws_implemented -eq $false -and $evidence.azure_implemented -eq $false) 'adapter evidence matches the final validator claims schema';$dump=Get-Content -Raw -LiteralPath (Join-Path $noApprovalRepo '.logs/env.txt');Assert-True ($dump -notmatch 'AWS_ACCESS_KEY_ID_REDACTED|AWS_ACCESS_KEY_ID') 'fake Codex process cannot observe seeded AWS credentials';$modelLogs=(Get-Content -Raw (Join-Path $noApprovalRepo '.logs/A-006/terra-1.stdout.jsonl'))+(Get-Content -Raw (Join-Path $noApprovalRepo '.logs/A-006/terra-1.stderr.log'));Assert-True ($modelLogs -notmatch 'raw-model-secret' -and $modelLogs -match '\[REDACTED\]') 'adapter sanitizes model stdout and stderr before persistence'}finally{Clear-AdapterEnvironment;Remove-Item -LiteralPath $noApprovalRepo -Recurse -Force;Remove-Item -LiteralPath $localData -Recurse -Force -ErrorAction SilentlyContinue}

foreach($killPoint in @('after_preparing_state','after_evidence','after_staging','after_committing_state','after_commit')){
    $killRepo=New-TestRepo "kill $killPoint";$killLocal=Join-Path $env:TEMP ('phase4-kill-'+[Guid]::NewGuid().ToString('N'))
    try{Write-TestPolicy $killRepo 'A-006' $false;&git -C $killRepo add project-a/harness/tasks/A-006.json;&git -C $killRepo commit -m policy|Out-Null;Set-AdapterEnvironment $killRepo 'A-006' $killLocal;$env:HARNESS_TEST_KILL_POINT=$killPoint;&pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Invoke-ProjectAAdapter.ps1') exec --json '[TASK:A-006]'|Out-Null;Assert-True ($LASTEXITCODE -eq 91) "$killPoint interruption is injected at the transaction boundary";Remove-Item Env:HARNESS_TEST_KILL_POINT;&pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Invoke-ProjectAAdapter.ps1') exec --json '[TASK:A-006]'|Out-Null;Assert-True ($LASTEXITCODE -eq 0 -and @(Get-Content (Join-Path $killRepo '.logs/calls.txt')).Count -eq 1 -and @(Get-ChangedPaths -Root $killRepo).Count -eq 0) "$killPoint resumes exact commit without another model call"}finally{Clear-AdapterEnvironment;Remove-Item -LiteralPath $killRepo -Recurse -Force;Remove-Item -LiteralPath $killLocal -Recurse -Force -ErrorAction SilentlyContinue}
}

$approvalRepo=New-TestRepo 'adapter approval';$localData=Join-Path $env:TEMP ('phase4-approval-'+[Guid]::NewGuid().ToString('N'))
try{Write-TestPolicy $approvalRepo 'A-001' $true;& git -C $approvalRepo add project-a/harness/tasks/A-001.json;& git -C $approvalRepo commit -m policy|Out-Null;Set-AdapterEnvironment $approvalRepo 'A-001' $localData;& pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Invoke-ProjectAAdapter.ps1') exec --json '[TASK:A-001]'|Out-Null;Assert-True ($LASTEXITCODE -eq 75) 'high-risk task pauses after validation and before commit';$state=Read-JsonFile -Path (Join-Path $approvalRepo '.harness/runtime/project-a/state/A-001.json');Assert-True ($state.status -eq 'awaiting_approval') 'approval pause is distinct from failure';Assert-True (@(Get-Content -LiteralPath (Join-Path $approvalRepo '.logs/calls.txt')).Count -eq 1) 'Terra ran exactly once before approval';$env:HARNESS_APPROVE_TASK='APPROVE:A-001';& pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Approve-ProjectATask.ps1') -TaskId A-001 -Root $approvalRepo|Out-Null;Assert-True ($LASTEXITCODE -eq 0) 'out-of-workspace broker signs exact-diff approval';$fixture=Join-Path $approvalRepo 'project-a/fixture with space-非.txt';[IO.File]::AppendAllText($fixture,'x');$request=Join-Path $localData 'RalphyHarness/cloud/approvals/project-a/requests/A-001.json';$receipt=Join-Path $localData 'RalphyHarness/cloud/approvals/project-a/receipts/A-001.json';$key=Join-Path $localData 'RalphyHarness/cloud/approvals/project-a/keys/A-001.dpapi';& pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Test-ProjectAApproval.ps1') -Root $approvalRepo -PolicyPath (Join-Path $approvalRepo 'project-a/harness/tasks/A-001.json') -RequestPath $request -ReceiptPath $receipt -KeyPath $key|Out-Null;Assert-True ($LASTEXITCODE -ne 0) 'one-byte post-approval edit invalidates receipt';[IO.File]::WriteAllText($fixture,"PROJECT_A_FAKE_OK`n",[Text.UTF8Encoding]::new($false));& pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Invoke-ProjectAAdapter.ps1') exec --json '[TASK:A-001]'|Out-Null;Assert-True ($LASTEXITCODE -eq 0) 'exact receipt resumes and commits';Assert-True (@(Get-Content -LiteralPath (Join-Path $approvalRepo '.logs/calls.txt')).Count -eq 1) 'approval resume makes no second model call';Assert-True ((& git -C $approvalRepo log -1 --format=%s).Trim() -eq 'feat(A-001): contract fixture') 'approved task uses policy commit message'}finally{Clear-AdapterEnvironment;Remove-Item -LiteralPath $approvalRepo -Recurse -Force;Remove-Item -LiteralPath $localData -Recurse -Force -ErrorAction SilentlyContinue}

$forgedRepo=New-TestRepo 'forged recovery';$forgedLocal=Join-Path $env:TEMP ('phase4-forged-'+[Guid]::NewGuid().ToString('N'))
try{Write-TestPolicy $forgedRepo 'A-001' $true;& git -C $forgedRepo add project-a/harness/tasks/A-001.json;& git -C $forgedRepo commit -m policy|Out-Null;Set-AdapterEnvironment $forgedRepo 'A-001' $forgedLocal;& pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Invoke-ProjectAAdapter.ps1') exec --json '[TASK:A-001]'|Out-Null;Assert-True ($LASTEXITCODE -eq 75) 'forged recovery fixture reaches approval pause';Write-JsonNoBom -Path (Join-Path $forgedRepo 'evidence/project-a/A-001.json') -Value ([ordered]@{forged=$true});& git -C $forgedRepo add project-a 'evidence/project-a/A-001.json';& git -C $forgedRepo commit -m 'feat(A-001): contract fixture'|Out-Null;& pwsh -NoLogo -NoProfile -NonInteractive -File (Join-Path $root 'scripts/Invoke-ProjectAAdapter.ps1') exec --json '[TASK:A-001]' 2>$null|Out-Null;Assert-True ($LASTEXITCODE -ne 0) 'same-subject manual commit is rejected without persisted intended tree and evidence digest';$forgedState=Read-JsonFile -Path (Join-Path $forgedRepo '.harness/runtime/project-a/state/A-001.json');Assert-True ($forgedState.status -ne 'completed') 'forged recovery cannot mark task complete'}finally{Clear-AdapterEnvironment;Remove-Item -LiteralPath $forgedRepo -Recurse -Force;Remove-Item -LiteralPath $forgedLocal -Recurse -Force -ErrorAction SilentlyContinue}

Write-Host "Project A harness tests passed: $passed assertions"
